### ISSUE TITLE
Update AWS-SDK-GO to v1.38.42 at minumum, but ideally to latest (v1.43.17) in awsutil

### ISSUE THREAD

**Issue by bengaywins** [hashicorp/go-secure-stdlib#34]
**Is your feature request related to a problem? Please describe.**
AWS Golang SDK is old and so does not support AWS SSO credentials without a special `credential_process`.

**Describe the solution you'd like**
The SDK updated and the ability to use SSO credentials normally

**Describe alternatives you've considered**
None. This is a non-starter because this is related to Vault supporting SSO creds through the use of this awsutil library that seemingly has been neglected for updates to the AWS SDK.

**Additional context**
We are trying to transition all our users to use AWS SSO (backed by JumpCloud) but Vault auth doesn't support it due to this library using the AWS SDK from _two_ years ago.

**Comment by jorhett** [comment]
https://github.com/aws/aws-sdk-go/issues/4989 is critical for SSO users, which means we need at least  v1.45.15.

**Comment by bengaywins** [comment]
That was the primary reason I opened this. I even had originally started working on a PR but things got in the way.
